version: '3.8'

services:
  node-app:
    environment:
      VITE_APP_API_URL: 'http://185.250.44.151:5000/api'
    image: node
    container_name: quasar
    volumes:
      - .:/app
    # ports:
    # - '3000:3000'
    working_dir: /app
    command: bash -c "npm i && npm run build"
